services:
    databases:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: tabanco
        ports:
            - "5432:5432"
